"""Optional PDF rendering of the HTML reports.

PDF is a *format*, not a second report: :func:`to_pdf` takes the same HTML the
API already serves and lays it out with ``reportlab``.  Nothing is recomputed, so
the PDF cannot disagree with the HTML or the bundle.

``reportlab`` is an optional dependency.  When it is missing this module raises a
specific ``DEPENDENCY_MISSING`` error and the caller (the API) answers with a
clear message and offers the HTML report instead - it never silently returns an
empty or truncated file, and it never claims a PDF exists when it does not.
"""

from __future__ import annotations

from xml.sax.saxutils import escape

from ..common.errors import ErrorCode, FeraError

#: Module name looked for at import time.
_REPORTLAB = "reportlab"


def reportlab_available() -> bool:
    """Whether PDF rendering is possible in this environment."""
    try:  # pragma: no cover - trivial
        import reportlab  # noqa: F401
    except Exception:  # noqa: BLE001
        return False
    return True


def _require_reportlab() -> object:
    """Import reportlab or raise an explicit, actionable error."""
    try:
        import reportlab  # noqa: F401
    except Exception as exc:  # noqa: BLE001
        raise FeraError(
            "PDF export requires the optional 'reportlab' package",
            code=ErrorCode.DEPENDENCY_MISSING,
            hint=(
                "python -m pip install reportlab   "
                "(the executive/technical HTML reports work without it)"
            ),
            details={"module": _REPORTLAB},
        ) from exc
    return reportlab


def html_to_pdf(html: str, title: str = "FERA report") -> bytes:
    """Render ``html`` to PDF bytes using a minimal, dependency-light writer.

    ``reportlab``'s full HTML parser is not used: the reports this module serves
    are generated by :mod:`fera.reports` and use a known, small subset of
    markup.  Parsing that subset here keeps the PDF path deterministic and
    avoids pulling in a parser whose output could vary between versions.
    """
    _require_reportlab()
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "FeraTitle",
        parent=styles["Title"],
        fontSize=16,
        spaceAfter=8,
    )
    heading_style = ParagraphStyle(
        "FeraHeading",
        parent=styles["Heading2"],
        fontSize=11,
        spaceBefore=10,
        spaceAfter=4,
    )
    body_style = ParagraphStyle(
        "FeraBody",
        parent=styles["BodyText"],
        fontSize=8.5,
        leading=11,
    )

    story: list[object] = [Paragraph(escape(title), title_style), Spacer(1, 4 * mm)]
    for line in _plain_lines(html):
        if not line:
            story.append(Spacer(1, 2 * mm))
            continue
        if line.startswith("## "):
            story.append(Paragraph(escape(line[3:].strip()), heading_style))
        else:
            story.append(Paragraph(escape(line), body_style))

    import io

    target = io.BytesIO()
    SimpleDocTemplate(
        target,
        pagesize=A4,
        title=title,
        author="FERA",
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=16 * mm,
        bottomMargin=16 * mm,
    ).build(story)
    return target.getvalue()


def _plain_lines(html: str) -> list[str]:
    """Reduce the generated HTML to plain text lines.

    Only enough markup is understood to keep headings, table cells and list
    items on their own lines; anything else is emitted as text.  Because the
    input is escaped before it reaches reportlab, a value containing markup
    cannot break the document.
    """
    import re

    text = re.sub(r"(?is)<(script|style).*?</\1>", " ", html)
    text = re.sub(r"(?i)</(h1|h2|h3|p|div|tr|li|table)>", "\n", text)
    text = re.sub(r"(?i)<br\s*/?>", "\n", text)
    text = re.sub(r"(?i)</(td|th)>", " | ", text)
    text = re.sub(r"<[^>]+>", "", text)
    text = (
        text.replace("&amp;", "&")
        .replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&nbsp;", " ")
        .replace("&mdash;", "-")
        .replace("&middot;", "-")
        .replace("&quot;", '"')
    )
    lines = [re.sub(r"\s+", " ", line).strip(" |").strip() for line in text.splitlines()]
    return [line for line in lines if line]


def to_pdf(bundle: dict[str, object], *, report_type: str, generated_at: str) -> bytes:
    """Render ``bundle`` as a PDF of the requested report type."""
    from .executive import build_executive
    from .technical import build_technical

    title = "FERA Executive Security Report" if report_type == "executive" else "FERA Technical Analysis Report"
    builder = build_executive if report_type == "executive" else build_technical
    return html_to_pdf(builder(bundle, generated_at=generated_at), title=title)


__all__ = ["html_to_pdf", "reportlab_available", "to_pdf"]
