#!/usr/bin/env python3
"""Regenerate the security baseline reference (``docs/security_baseline.md``).

    python scripts/generate_security_policy_docs.py
    python scripts/generate_security_policy_docs.py --out docs/security_baseline.md
    python scripts/generate_security_policy_docs.py --check
    python scripts/generate_security_policy_docs.py --json

Every table in the document is rendered from ``fera.security.policy``,
``fera.security.rules`` and ``fera.security.threats``, so the reference cannot
drift away from the code that scores a capture.  ``--check`` regenerates the
document in memory and fails when the file on disk differs, which is what keeps
a pull request honest when a weight or a tier changes.
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

import _bootstrap  # noqa: E402
from fera.common.errors import FeraError  # noqa: E402
from fera.common.paths import default_paths  # noqa: E402
from fera.common.serialization import write_text_file  # noqa: E402
from fera.security import (  # noqa: E402
    POLICY_ALIASES,
    RISK_MATRIX,
    deduction_model,
    describe_rules,
    described_threats,
    policy_catalogue,
)

DEFAULT_OUTPUT = Path("docs") / "security_baseline.md"


def _table(headers: Sequence[str], rows: Sequence[Sequence[Any]]) -> list[str]:
    """A markdown table with a header separator sized to the header cells."""
    lines = ["| " + " | ".join(headers) + " |", "| " + " | ".join("---" for _ in headers) + " |"]
    for row in rows:
        lines.append("| " + " | ".join(str(cell) for cell in row) + " |")
    return lines


def _section(title: str) -> list[str]:
    return ["", f"## {title}", ""]


def _algorithm_rows(entries: Sequence[Mapping[str, Any]]) -> list[list[str]]:
    rows: list[list[str]] = []
    for entry in entries:
        strength = entry.get("strength_bits")
        rows.append(
            [
                f"`{entry['name']}`",
                entry["tier"],
                "-" if strength is None else str(strength),
                str(entry["reason"]),
            ]
        )
    return rows


def _spelling_rows(vocabulary: Mapping[str, str]) -> list[list[str]]:
    """Group the accepted spellings of one vocabulary by canonical name."""
    grouped: dict[str, list[str]] = {}
    for alias, canonical in vocabulary.items():
        grouped.setdefault(canonical, []).append(alias)
    rows: list[list[str]] = []
    for canonical in sorted(grouped):
        spellings = sorted(grouped[canonical])
        rendered = ", ".join(f"`{item}`" for item in spellings if item != canonical)
        rows.append([f"`{canonical}`", rendered or f"`{canonical}`"])
    return rows


def render_markdown() -> str:
    """The whole reference document, rendered from the live tables."""
    catalogue = policy_catalogue()
    model = deduction_model()
    lines: list[str] = [
        "# FERA security baseline",
        "",
        f"Generated from `fera.security.policy` ({catalogue['policy_id']} "
        f"{catalogue['policy_version']}) by `scripts/generate_security_policy_docs.py`.",
        "Do not edit this file by hand: change the tables and regenerate it.",
        "",
        "```",
        "python scripts/generate_security_policy_docs.py",
        "```",
        "",
        "Everything below is data the assessment engine reads at run time.  The same "
        "tables travel inside every report (`policy_id` plus the rule ids that were "
        "applied), so a report can always be traced back to the baseline that scored it.",
    ]

    lines += _section("How a score is computed")
    lines += [
        "```",
        model["formula"],
        "```",
        "",
        "with, for each finding,",
        "",
        "```",
        model["point_formula"],
        "```",
        "",
        "and the following guarantees:",
        "",
    ]
    lines += [f"- {item}" for item in model["rules"]]
    lines += [""]

    lines += _section("Category weights")
    lines += _table(
        ["category", "weight", "ceiling (points)"],
        [[category, weight, round(weight * 100, 2)] for category, weight in model["category_weights"].items()],
    )

    lines += _section("Verdict factors")
    lines += _table(["verdict", "factor"], sorted(model["status_factors"].items()))
    lines.append("")
    lines.append(
        "`PASS` and `NOT_VERIFIABLE` are zero on purpose: a rule that found nothing, "
        "and a rule that could not look, both cost nothing."
    )
    lines += _section("Evidence factors")
    lines += _table(["evidence", "factor"], sorted(model["evidence_factors"].items()))
    lines.append("")
    lines.append(
        "`INFERRED` is multiplied by the model's own confidence as well, so a hesitant "
        "prediction costs less than a confident one - and both stay labelled inferred."
    )
    lines += _section("Coverage weights")
    lines += _table(["evidence", "weight"], sorted(model["coverage_weights"].items()))
    lines.append("")
    lines.append(
        "`evidence_coverage` is the mean of these weights over the verdicts that were "
        "reached.  `NOT_VERIFIABLE` counts zero, which is what keeps an unanswerable "
        "capture from reading as a clean one."
    )

    lines += _section("Risk bands")
    lines += _table(
        ["minimum security score", "risk level"],
        [[band["min_score"], band["risk"]] for band in model["risk_bands"]],
    )

    lines += _section("Algorithm baseline")
    tiers = catalogue["tier_base_points"]
    lines += _table(
        ["tier", "severity", "base points"],
        [
            [tier, catalogue["tier_severity"][tier], tiers[tier]]
            for tier in ("FORBIDDEN", "DEPRECATED", "ACCEPTABLE", "RECOMMENDED", "UNKNOWN")
        ],
    )
    lines.append("")
    lines.append(
        f"`{catalogue['aead_sentinel']}` is the testbed's word for \"the AEAD cipher "
        "authenticates the payload, so no separate integrity transform is expected\"."
    )
    for heading, key in (
        ("Encryption transforms", "encryption"),
        ("Integrity transforms", "integrity"),
        ("Pseudorandom functions", "prf"),
        ("Diffie-Hellman groups", "diffie_hellman"),
    ):
        lines += ["", f"### {heading}", ""]
        lines += _table(["transform", "tier", "strength (bits)", "why"], _algorithm_rows(catalogue[key]))

    lines += _section("SA lifetimes")
    for scope, label in (("ike", "IKE SA"), ("child", "Child SA")):
        entry = catalogue["lifetimes"][scope]
        lines += [
            f"**{label}**: target {entry['preferred_s']}s, accepted up to "
            f"{entry['acceptable_s']}s, maximum {entry['maximum_s']}s. {entry['rationale']}",
            "",
        ]
    lines += _section("Rule catalogue")
    lines += [
        f"{len(describe_rules())} rules, run in this order.  The order is the report "
        "order, and it breaks ties when two rules settle the same property.",
        "",
    ]
    lines += _table(
        ["rule", "category", "title", "points (verdict -> points)", "what it checks"],
        [
            [
                f"`{rule['rule_id']}`",
                rule["category"],
                rule["title"],
                ", ".join(
                    f"{verdict}:{points:g}"
                    for verdict, points in rule["points"].items()
                    if points
                )
                or "informational",
                rule["summary"],
            ]
            for rule in describe_rules()
        ],
    )

    lines += _section("Threat matrix")
    lines += _table(
        ["threat", "category", "likelihood", "impact", "risk", "reported for", "what an attacker would achieve"],
        [
            [
                f"`{threat['threat_id']}`",
                threat["category"],
                threat["likelihood"],
                threat["impact"],
                threat["risk"],
                ", ".join(f"`{rule}`" for rule in threat["rule_ids"]),
                threat["threat"],
            ]
            for threat in described_threats()
        ],
    )
    lines.append("")
    lines.append(
        "Entries marked from an unverifiable property are reported when the property "
        "could not be checked, and their evidence line says so."
    )
    lines += ["", "### Likelihood x impact", ""]
    order = ("HIGH", "MEDIUM", "LOW")
    lines += _table(
        ["likelihood \\ impact", *order],
        [[likelihood, *[RISK_MATRIX[(likelihood, impact)].value for impact in order]] for likelihood in order],
    )

    lines += _section("Accepted spellings")
    lines.append(
        "The engine folds names separator-insensitively, so the testbed keywords, the "
        "strongSwan keywords, IANA names and group numbers all resolve to one entry.  A "
        "name that matches nothing lands in `UNKNOWN` and is reported, never charged."
    )
    for vocabulary in ("encryption", "integrity", "prf", "diffie_hellman"):
        lines += ["", f"### {vocabulary}", ""]
        lines += _table(["canonical", "also spelled"], _spelling_rows(POLICY_ALIASES[vocabulary]))

    lines += _section("Observation thresholds")
    lines += _table(
        ["threshold", "value"],
        [
            ["distinct payload sizes below which traffic collapses into classes", catalogue["metadata_thresholds"]["distinct_length_classes_min"]],
            ["share of block-aligned packets suggesting padding", catalogue["metadata_thresholds"]["padding_aligned_share_max"]],
            ["prediction confidence below which a guess is not acted on", catalogue["metadata_thresholds"]["prediction_confidence_min"]],
            ["surprisal (bits) above which a prediction is called inconclusive", catalogue["metadata_thresholds"]["prediction_surprisal_max_bits"]],
            ["ESP packets needed before sequence behaviour is judged", catalogue["min_packets_for_sequence_analysis"]],
        ],
    )
    return "\n".join(lines) + "\n"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Regenerate the security baseline reference document.")
    parser.add_argument("--out", default=None, help=f"document to write (default: {DEFAULT_OUTPUT.as_posix()})")
    parser.add_argument("--check", action="store_true", help="exit 1 when the document on disk is out of date")
    parser.add_argument("--json", action="store_true", help="print the tables instead of writing the document")
    parser.add_argument("--log-level", default="WARNING")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    _bootstrap.bootstrap_logging(args.log_level)
    paths = default_paths()
    document = render_markdown()
    catalogue = policy_catalogue()

    if args.json:
        _bootstrap.print_json(
            {
                "policy": catalogue,
                "scoring_model": deduction_model(),
                "rules": describe_rules(),
                "threats": described_threats(),
            }
        )
        return 0

    target = paths.resolve(args.out) if args.out else paths.root / DEFAULT_OUTPUT
    if args.check:
        if not target.is_file():
            print(f"MISSING: {paths.relative(target)} has not been generated", file=sys.stderr)
            return 1
        if target.read_text(encoding="utf-8") != document:
            print(
                f"OUTDATED: {paths.relative(target)} differs from the live tables - rerun "
                "python scripts/generate_security_policy_docs.py",
                file=sys.stderr,
            )
            return 1
        print(f"up to date      : {paths.relative(target)}")
        return 0

    write_text_file(target, document)
    _bootstrap.print_section("Security baseline reference")
    print(f"document        : {paths.relative(target)}")
    print(f"lines           : {len(document.splitlines())}")
    print(f"policy          : {catalogue['policy_id']} {catalogue['policy_version']}")
    print(f"rules           : {len(describe_rules())}")
    print(f"threats         : {len(described_threats())}")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except FeraError as error:  # pragma: no cover - CLI error path
        print(f"ERROR [{error.code.value}]: {error.message}", file=sys.stderr)
        sys.exit(1)

